### ISSUE TITLE
Add to @types repository?

### ISSUE THREAD

**Issue by malinbranduse** [D10221/wavesurfer-typescript#1]
Hello! thanks for making the definition for this package!
Just wondering why this isn't added to the official repository for types?

**Comment by D10221** [comment]
Hi and thank you,

Here is a list of excuses ; ) 

- Its incomplete, 
- I couldn't make pass all the test at the time, I haven't tried since, I was also playing with jsdom, .
- its way behind from "2.0.0-beta01", currently., wavesurfer  sits on 2.5 as per their package.json/version
- it was a weekend fun/hack, 
- it doesn't conform to typing's guidelines,
- I didn't intend o maintain it.  :ashamed
- wavesurrfer has a open [issue ](https://github.com/katspaugh/wavesurfer.js/issues/1209) where they talk about adding typescript support
- I thought at the time ... still works as a hack because when installing from github with npm it ends up into @types/, locally :)
 or I could simply paste it into my 'next-project' ,

**Comment by malinbranduse** [comment]
Understood! All are valid reasons. :grinning: 

If I knew I'd be working with wavesurfer more than once I'd propose we update and maintain the type definitions together but yea, it works just fine as it is now.

Thanks again sharing this!
